schema_version = "1.0.0"
id = "Tracker2Nuke"
version = "1.0.0"
name = "Tracker to Nuke"
tagline = "Instantly export Blender tracking data to a Nuke Tracker node"
maintainer = "Naoki Korematsu" 
type = "add-on"
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
tags = ["Tracking", "Import-Export"]